spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url,qq

        - id: product_route
          uri: lb://cumtbmall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          ##负载均衡到renren-fast（因为在nacos中注册过）
          uri: lb://renren-fast
          predicates:
            ##按照路径来断言
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}


## 前端项目，/api
##商品服务路径重写：:88/api/product/category/list/tree   10000/product/category/list/tree